name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build Frontend Image
      run: |
        docker build -t haseebsajid/project_frontend:latest ./frontend

    - name: Build Server Image
      run: |
        docker build -t haseebsajid/project_server:latest ./server

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Frontend Image
      run: docker push haseebsajid/project_frontend:latest

    - name: Push Server Image
      run: docker push haseebsajid/project_server:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment-frontend.yaml -n scd-project
        kubectl apply -f k8s/service-frontend.yaml -n scd-project
        kubectl apply -f k8s/deployment-server.yaml -n scd-project
        kubectl apply -f k8s/service-server.yaml -n scd-project
